### ISSUE TITLE
Tooltips not working on iOS

### ISSUE THREAD

**Issue by iamjohnbarker** [lmsqueezy/wedges#32]
**Describe the bug**
When attempting to trigger a tooltip on iOS with a touch action, the tooltip flashes and then instantly disappears. 

**To Reproduce**
1. Open example tooltip docs on chrome iOS
2. Press the "I"

**Expected behavior**
I would expect the tooltip to appear. Then disappear on another tap. 

**Screenshots**
Not applicable. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - iPhone 13
 - 17.1.2
 - Chrome
 - 120.0.6099.119

**Additional context**
Seems to happen on Safari iOS also

**Comment by fecony** [comment]
Radix tooltip doesn't even appear like that on mobile 😄 
https://www.radix-ui.com/primitives/docs/components/tooltip

**Comment by Warlockx** [comment]
facing the same issue on android

**Comment by brankoconjic** [comment]
You can read more about this here: https://github.com/radix-ui/primitives/issues/2029
