### ISSUE TITLE
NextJS template missing

### ISSUE THREAD

**Issue by bstefan** [lmsqueezy/wedges#37]
**Describe the bug**
NextJS template not on Github?

**Terminal error when trying the docs step by step guide**
Found invalid GitHub URL: "https://github.com/lmsqueezy/wedges/templates/next-app-template". Please fix the URL and try again.

**Comment by brankoconjic** [comment]
Hey,

Thanks for reporting this. The [doc](https://www.lemonsqueezy.com/wedges/docs/installation/nextjs) has been updated with the correct URL.
